### ISSUE TITLE
Please make it compatible with subsonic 4.7

### ISSUE THREAD

**Issue by Fr3shF1sh** [hakko/musiccabinet#11]
Hello,
could you please integrate it in Subsonic 4.7 when they release the stable version :) ?
I am also ready to donate you a little money for your work !! 

Cheers

**Comment by hakko** [comment]
Hi!

Subsonic 4.7 introduces the concept of a media scanner (so that browsing your library is no longer based on file structure), which is a good idea. However, instead of using that, I decided to write a similar (but faster) solution from scratch, which works better together with how the information from last.fm is stored.

I've just released a beta version of this. There are some known issues, so you might want to wait for a more stable release. See http://forum.subsonic.org/forum/viewtopic.php?f=4&t=9777#p43886.

If you do appreciate this project, please consider donating money to charity. There are humans and animals in much more need of it than me. Thank you.

Regards / hakko

**Comment by Fr3shF1sh** [comment]
Hi,
thank you for your fast reply!! I didn't know about the new concept.
I will try the beta version, since I really like your MOD and the new Star-rating.

Could you improve the Star-rating (or is this "core-subsonic"-related?)
I posted my issue there:
http://forum.subsonic.org/forum/viewtopic.php?f=4&t=9686&p=43986#p43986

"Please make it possible, that every User has its own "Starred Items". When i then click in the top menue on Starred there should be a dropdown menu, where i can chose what stars I want to see: a) only mine b) all stars )c stars from specific users. "

EDIT: 
Is your 'star' different from the "original" subsonic star introduced with 4.7? (I ask that, because you write that I need a last.fm account).
On your new media scanner solution:
Please be sure that it will work for FLAC Files, too  :) I love FLAC :D 

Thank you very much for your work !! 
Cheers

**Comment by hakko** [comment]
Yes, I've written the star handling myself, it's not taken from Subsonic. The stars are "per user" and right now, you can only see your own starred items. It is technically possible to view other users items as well, but there's no way to do it in the current interface. FLAC is supported.

**Comment by Fr3shF1sh** [comment]
Thank you for your reply and the info!
Is there also a possibility for a starring without last.fm account? (I dont own one :D )

**Comment by hakko** [comment]
I decided that a last.fm account is necessary, because that will allow me to import play statistics and loved tracks from last.fm (most people use multiple music players and by having them all scrobble to last.fm, I could import play statistics from what you've listened to in Winamp or Foobar into Subsonic).

Also, by having people create a last.fm account (it's totally free and anonymous) I can get personal music recommendations from there and integrate into MusicCabinet/Subsonic, which I think will make it an even more interesting music platform. So I decided it was a good idea to deepen the last.fm integration even more than before and have it that way. You don't have to do anything about your last.fm account, it just registers songs that you're listening to and after a while, it comes up with interesting ideas on other things you might like.

**Comment by Fr3shF1sh** [comment]
Hello,
thank you for you answer again :) On this view, it's a good possibility to chose last.fm. 
But as I am not a total fan of cloud services, I would still like a normal star rating :) 

I installed your beta and got one issue that I would like to be changed:
In the "old" subsonic i could also select only special folders ( in the left artist menue frame). 
Now I can only select genres. 
Please make it possible to still chose the folders.

Why:
I for example have normal MP3 and FLAC. Sometimes I'm just looking for FLAC. Then I select only the folder with FLAC tracks in it. Only if I cant find the song as a FLAC - file i'm switching (using the search).

Cheers

**Comment by hakko** [comment]
Sorry to let you down but those are two design decisions that aren't bound to change anytime soon. It would take you maybe two minutes to create a last.fm account and configure Subsonic/MusicCabinet to use it. Then never use it again and the star rating would work. Also, this version of MusicCabinet is based on file tags rather than file structure, so if you depend on having a certain file structure, this mod is probably not what you're looking for. Your other alternative is of course forking and adding that feature yourself (I'd encourage such a project, that would be fun).
